function [BW,maskedRGBImage] = ShadowMask3(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 20-May-2024
%------------------------------------------------------


% Convert RGB image to chosen color space
hsvImg = rgb2hsv(RGB);

% Extract the Value (V) channel
V = hsvImg(:, :, 3);

% Apply adaptive thresholding
% Here, we will use `adaptthresh` which computes a locally adaptive threshold
T = adaptthresh(V, 0.4); % 0.4 is a sensitivity factor that can be tuned


BW = imbinarize(V, T);

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end
